export interface SharkiaExchange {
  id: string;
  name: string;
  owner: string;
  city: string;
  locationDetails: string;
  phone: string;
  date: string;
  type: string;
  badgeEmoji: string;
  popularity: "ممتازة" | "نشطة" | "معتمدة" | "شعبية";
  contactsCount: string;
  bulletinText: string;
  prices: {
    white_poultry?: number;
    sass_poultry?: number;
    baladi_poultry?: number;
    mothers_poultry?: number;
    white_chick_corp?: number;
    white_chick_dist?: number;
    sass_chick?: number;
    sass_chick_2nd?: number;
    baladi_chick?: number;
    baladi_chick_hybrid?: number;
    rozzi_chick?: number;
    rozzi_chick_braber?: number;
    duck_french?: number;
    duck_pekin_farms?: number;
    duck_pekin_egg?: number;
    duck_muscovy_1day?: number;
    feed_badi?: number;
    feed_nami?: number;
    feed_nahi?: number;
    egg_white?: number;
    egg_red?: number;
    egg_baladi?: number;
  };
}

export const SHARKIA_EXCHANGES_LIST: SharkiaExchange[] = [
  {
    id: "maher-shaikh",
    name: "بورصة الحاج ماهر الشيخ",
    owner: "الحاج ماهر الشيخ",
    city: "ههيا",
    locationDetails: "ههيا، الشرقية - مقابل بنك مصر القديم",
    phone: "01095543200",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "كتاكيت، بط نخب أول ومائي، أعلاف ممتازة",
    badgeEmoji: "🌟",
    popularity: "ممتازة",
    contactsCount: "أكثر من ١٠ آلاف مربي بمركز ههيا والقرى المجاورة",
    bulletinText: "🚨 نشرة بورصة ههيا الرسمية اليومية بالتحديث الجديد:\n\nنعلن للمربين الأفاضل عن ثبات أسعار الكتاكيت اليوم:\n🐥 كتكوت أبيض شركات: 12.00 ج.م سوبر\n🐥 كتكوت تسمين أهالي: 12.00 ج.م\n🐥 كتكوت ساسو شفر: 6.00 ج.م\n🐥 كتكوت بلدي بيور بياض: 4.50 ج.م\n🐥 كتكوت رزي متميز ولحم: 7.00 ج.م\n\n🦆 مائي وبط:\n- بط مولر ألماني تسمين: 12.00 ج.م\n- بط بكيني مزارع محسن: 6.00 ج.م\n- بيض تفريخ بط بكيني: 6.00 ج.م\n\nعافية القطعان تبدأ بالتغذية السليمة! نوفر أفضل الخامات.",
    prices: {
      white_poultry: 84,
      sass_poultry: 105,
      baladi_poultry: 140,
      mothers_poultry: 72,
      white_chick_corp: 12,
      white_chick_dist: 12,
      sass_chick: 6,
      sass_chick_2nd: 5.5,
      baladi_chick: 4.5,
      baladi_chick_hybrid: 4.5,
      rozzi_chick: 7,
      rozzi_chick_braber: 5.5,
      duck_french: 12,
      duck_pekin_farms: 6,
      duck_pekin_egg: 6,
      duck_muscovy_1day: 16,
      feed_badi: 22800,
      feed_nami: 22700,
      feed_nahi: 22550,
      egg_white: 151,
      egg_red: 156
    }
  },
  {
    id: "abu-kabir-exchange",
    name: "بورصة أبو كبير العمومية للدواجن والكتكوت",
    owner: "المهندس شريف عبدالرحمن",
    city: "أبو كبير",
    locationDetails: "أبو كبير، بجوار كوبري المرور القديم - الشرقية",
    phone: "01011223344",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "لحم تسمين (أبيض، ساسو)، كتاكيت بلدي ورزي متميزة",
    badgeEmoji: "🏷️",
    popularity: "ممتازة",
    contactsCount: "تغطية كاملة لمحلات وتجار التسمين بأبو كبير وفاقوس والشرقية",
    bulletinText: "📈 أسعار البيع والتنفيذ اليوم بمحلات وأقفاص أبو كبير:\n\nتشهد أسعار التسمين استقراراً مع سحب ممتاز:\n🐓 لحم أبيض تسمين: تنفيذ 84 ج.م بالمزرعة\n🐓 لحم ساسو أحمر سوبر: تنفيذ 105 ج.م\n🐓 بلدي حر تربية منازل: تنفيذ 140 ج.م\n\n🐥 بورصة الكتاكيت عمر يوم:\n- كتكوت تسمين متميز شركات: 12.10 ج.م\n- كتكوت أبيض أهالي: 11.50 ج.م\n- كتكوت ساسو شفر ممتاز: 5.90 ج.م\n- كتكوت بلدي بيور بياض: 4.40 ج.م\n\n🌾 الأعلاف بالمخازن:\n- طن علف بادي سوبر 23%: 22,600 ج.م\n\nنلتزم بالوزن وتوفير أفضل قطعان التسمين بالدلتا.",
    prices: {
      white_poultry: 84,
      sass_poultry: 105,
      baladi_poultry: 140,
      mothers_poultry: 72,
      white_chick_corp: 12.1,
      white_chick_dist: 11.5,
      sass_chick: 5.9,
      sass_chick_2nd: 5.4,
      baladi_chick: 4.4,
      baladi_chick_hybrid: 4.4,
      rozzi_chick: 6.9,
      rozzi_chick_braber: 5.4,
      duck_french: 11.9,
      duck_pekin_farms: 5.9,
      duck_pekin_egg: 5.8,
      duck_muscovy_1day: 15.9,
      feed_badi: 22600,
      feed_nami: 22200,
      feed_nahi: 21900,
      egg_white: 150,
      egg_red: 155
    }
  },
  {
    id: "ibrahimiyah-amer",
    name: "بورصة الإبراهيمية للدواجن (مكتب آل عامر)",
    owner: "المستشار الحاج محمد عامر",
    city: "الإبراهيمية",
    locationDetails: "الإبراهيمية، الشارع الرئيسي - بجوار محكمة الإبراهيمية",
    phone: "01289122334",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "كتاكيت بيضاء، بط بكيني وفرنسي مائي، أعلاف البركة",
    badgeEmoji: "📌",
    popularity: "معتمدة",
    contactsCount: "الوكيل الحصري لأعلاف البركة بمركز الإبراهيمية والقرى المجاورة",
    bulletinText: "🌟 تحديث أسعار الإبراهيمية ومحيطها اليوم الأربعاء:\n\nكتاكيت عالية التحويل والوزن تسليم فوري للمزارع:\n🐥 كتكوت أبيض سوبر شركات: 11.95 ج.م\n🐥 كتكوت تسمين قطعان معقم: 11.45 ج.م\n🐥 كتكوت ساسو شفر: 5.85 ج.م\n🐥 كتكوت بلدي هجين للبيض واللحم: 4.35 ج.م\n\n🦆 البط المائي والأوز:\n- بط مولر ألماني ممتاز: 12.30 ج.م\n- بط تسمين بكيني مزارع: 6.00 ج.م\n\n🌾 أعلاف المزارع التسمين:\n- طن علف بادي 23%: 22,500 ج.م",
    prices: {
      white_poultry: 84,
      sass_poultry: 105,
      baladi_poultry: 139,
      mothers_poultry: 71.5,
      white_chick_corp: 11.95,
      white_chick_dist: 11.45,
      sass_chick: 5.85,
      sass_chick_2nd: 5.3,
      baladi_chick: 4.35,
      baladi_chick_hybrid: 4.35,
      rozzi_chick: 6.8,
      rozzi_chick_braber: 5.3,
      duck_french: 12.3,
      duck_pekin_farms: 6,
      duck_pekin_egg: 5.9,
      duck_muscovy_1day: 16,
      feed_badi: 22500,
      feed_nami: 22100,
      feed_nahi: 21800,
      egg_white: 151,
      egg_red: 156
    }
  },
  {
    id: "kafr-nigm-exchange",
    name: "بورصة كفور نجم لتربية وتوزيع الدواجن",
    owner: "الدكتور سامح النجمي",
    city: "كفور نجم",
    locationDetails: "طريق كفور نجم الرئيسية، مركز الإبراهيمية، الشرقية",
    phone: "01004958111",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "كتكوت أبيض بياض، بط للتربية المنزلية، خامات بيطرة",
    badgeEmoji: "☘️",
    popularity: "نشطة",
    contactsCount: "تخدم صغار وكبار المربين بقرية كفور نجم وضواحي مركز الإبراهيمية",
    bulletinText: "🐔 بورصة كفور نجم للدواجن والكتاكيت اليوم الأربعاء:\n\nنوفر أفضل السلالات المحسنة المقاومة للتغير الحراري بمصر:\n🐥 كتكوت تسمين شركات نخب أول: 12.10 ج.م\n🐥 كتكوت أبيض أهالي مفرز: 11.40 ج.م\n🐥 كتكوت ساسو جيل ثاني ممتاز: 5.50 ج.م\n🐥 كتكوت بلدي بيور بياض: 4.40 ج.م\n\n🥚 أسعار البيض اليوم كرتونة:\n- طبق بيض أحمر سوبر: 156 ج.م\n- طبق بيض أبيض: 151 ج.م\n- طبق بيض بلدي أصلي: 136 ج.م",
    prices: {
      white_poultry: 84.2,
      sass_poultry: 105,
      baladi_poultry: 140,
      mothers_poultry: 72,
      white_chick_corp: 12.1,
      white_chick_dist: 11.4,
      sass_chick: 5.8,
      sass_chick_2nd: 5.5,
      baladi_chick: 4.4,
      baladi_chick_hybrid: 4.4,
      rozzi_chick: 6.85,
      rozzi_chick_braber: 5.4,
      duck_french: 11.8,
      duck_pekin_farms: 5.8,
      duck_pekin_egg: 5.6,
      duck_muscovy_1day: 15.7,
      feed_badi: 22550,
      feed_nami: 22150,
      feed_nahi: 21850,
      egg_white: 151,
      egg_red: 156,
      egg_baladi: 136
    }
  },
  {
    id: "manshat-radwan-office",
    name: "بورصة منشأة رضوان للدواجن والكتكوت (سعيد الحبيبي)",
    owner: "المهندس سعيد الحبيبي",
    city: "أبو كبير",
    locationDetails: "منشأة رضوان، على طريق ههيا/أبو كبير الرئيسي - الشرقية",
    phone: "01140022355",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "لحم بيضاء تسمين، كتاكيت شركات كبرى سلالات المشرق",
    badgeEmoji: "⚡",
    popularity: "ممتازة",
    contactsCount: "ملتقى تجار ومربي طريق ههيا - أبو كبير السريع لتوفير الميازين",
    bulletinText: "⚡ نشرة منشأة رضوان للدواجن والكتكوت (سعيد الحبيبي):\n\nنعلن للمربين الأفاضل ثبات التنفيذ اليوم تمهيداً لحركة تسليمات الغد لضمان الربح السليم للجميع:\n🐓 لحم أبيض تسمين: 84.00 ج.م بالمزرعة\n🐓 لحم ساسو أحمر سوبر: 105.00 ج.م\n\n🐥 بورصة الكتاكيت عمر يوم فرز أول متميز:\n- كتكوت أبيض شركات المشرق: 12.20 ج.م\n- كتكوت أبيض هجين أهالي: 11.60 ج.م\n- كتكوت بلدي بيور بياض مستمر بمناعة كاملة: 4.50 ج.م\n\nنلتزم بالشفافية المطلقة وتوفير الغذاء الأفضل للفوج.",
    prices: {
      white_poultry: 84,
      sass_poultry: 105,
      baladi_poultry: 140,
      mothers_poultry: 72,
      white_chick_corp: 12.2,
      white_chick_dist: 11.6,
      sass_chick: 5.9,
      sass_chick_2nd: 5.4,
      baladi_chick: 4.5,
      baladi_chick_hybrid: 4.4,
      rozzi_chick: 6.9,
      rozzi_chick_braber: 5.5,
      duck_french: 12,
      duck_pekin_farms: 6,
      duck_pekin_egg: 5.8,
      duck_muscovy_1day: 16.1,
      feed_badi: 22600,
      feed_nami: 22200,
      feed_nahi: 21900,
      egg_white: 151,
      egg_red: 156
    }
  },
  {
    id: "el-atwa-exchange",
    name: "بورصة قرية العتوة للأعلاف والدواجن (ههيا)",
    owner: "الحاج أبو أحمد العتوي",
    city: "ههيا",
    locationDetails: "ههيا، قرية العتوة - بجوار الكنيسة القديمة ومحطة المياه",
    phone: "01002244668",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "أعلاف النخبة للمزارع، كتاكيت التسمين والأهالي المفرزة",
    badgeEmoji: "📦",
    popularity: "شعبية",
    contactsCount: "تخدم أصحاب العنبر والمربين بقرى العتوة وعزب مركز ههيا وضواحيها",
    bulletinText: "📦 أسعار وتوريدات مكتب العتوة للأعلاف اليوم الأربعاء:\n\nنوفر خامات متميزة فائقة القوة لضمان نمو قياسي للكتكوت الأبيض:\n🐣 كتكوت أبيض تسمين شركات: 11.90 ج.م\n🐣 كتكوت أبيض أهالي مبخر: 11.35 ج.م\n🐣 كتكوت بلدي هجين تسمين سريع: 4.30 ج.م\n🐣 كتكوت رزي متميز ولحم: 6.80 ج.م\n\n🌾 الأسعار الرسمية للأعلاف الممتازة اليوم للطن:\n- طن علف بادي 23%: 22,400 ج.م\n- طن علف نامي 21%: 22,000 ج.م\n- طن علف ناهي 19%: 21,700 ج.م\n\nخصومات مذهلة للدفع الكاش والتسليم الفوري من المخازن الرئيسية.",
    prices: {
      white_poultry: 83.5,
      sass_poultry: 104,
      baladi_poultry: 139,
      mothers_poultry: 71.5,
      white_chick_corp: 11.9,
      white_chick_dist: 11.35,
      sass_chick: 5.7,
      sass_chick_2nd: 5.2,
      baladi_chick: 4.3,
      baladi_chick_hybrid: 4.3,
      rozzi_chick: 6.8,
      rozzi_chick_braber: 5.3,
      duck_french: 11.7,
      duck_pekin_farms: 5.7,
      duck_pekin_egg: 5.5,
      duck_muscovy_1day: 15.6,
      feed_badi: 22400,
      feed_nami: 22000,
      feed_nahi: 21700,
      egg_white: 150,
      egg_red: 155
    }
  },
  {
    id: "el-morshed",
    name: "بورصة المرشد للدواجن والكتاكيت",
    owner: "مجموعة مكاتب المرشد للشرق الأوسط",
    city: "الزقازيق",
    locationDetails: "الزقازيق، طريق الشوبك - ممتد للزقازيق الجديدة",
    phone: "01154330221",
    date: "برسيل اليوم الأربعاء ٣-٦-٢٠٢٦",
    type: "لحم تسمين أبيض، أمهات لحم، كتاكيت الموزعين",
    badgeEmoji: "📊",
    popularity: "نشطة",
    contactsCount: "متابعة يومية للأسعار وتنفيذ المزارع الكبيرة بالشرقية",
    bulletinText: "✨ تنفيذ مكاتب المرشد اليوم الأربعاء:\n\n📉 تراجع طفيف في بعض خامات التسمين بالشرق الأوسط:\n🐓 لحم أبيض تسمين: تنفيذ 84 ج.م (توصيل المزرعة للمربين)\n🐓 لحم ساسو أحمر سوبر: تنفيذ 106 ج.م\n🐓 أمهات بيضاء هبرد ثقيلة: تنفيذ 73 ج.م\n\n🐥 بورصة الكتاكيت:\n- كتكوت تسمين شركات مميز: 12.80 ج.م\n- كتكوت تسمين موزعين (قطعان): 12.10 ج.م\n- كتكوت ساسو جيل أول: 5.80 ج.م\n- كتكوت بلدي هجين للتسمين: 4.30 ج.م\n\nنحمي المربي الصغير ونضمن أسعار عادلة دائمًا.",
    prices: {
      white_poultry: 84,
      sass_poultry: 106,
      baladi_poultry: 142,
      mothers_poultry: 73,
      white_chick_corp: 12.8,
      white_chick_dist: 12.1,
      sass_chick: 5.8,
      sass_chick_2nd: 5.2,
      baladi_chick: 4.3,
      baladi_chick_hybrid: 4.3,
      rozzi_chick: 6.8,
      rozzi_chick_braber: 5.2,
      duck_french: 12.5,
      duck_pekin_farms: 6.2,
      duck_pekin_egg: 5.8,
      duck_muscovy_1day: 16.5,
      feed_badi: 22400,
      feed_nami: 22000,
      feed_nahi: 21750,
      egg_white: 152,
      egg_red: 157
    }
  },
  {
    id: "monir-sakka",
    name: "بورصة السقا والبط والزيوت",
    owner: "مكتب المستشار منير السقا للدواجن",
    city: "بلبيس",
    locationDetails: "بلبيس، مدخل ميدان الطيارة - بجوار مبيعات بلبيس الزراعية",
    phone: "01205567788",
    date: "تحديث اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "بط وبكيني وتفريخ ومستلزمات أعلاف الدلتا",
    badgeEmoji: "🦆",
    popularity: "معتمدة",
    contactsCount: "مركز بلبيس والعاشر من رمضان، الريادة في المائي",
    bulletinText: "🦆 أسعار مكاتب ومنير السقا للمائي والبلدي ببلبيس:\n\nاليوم تسليمات البط فرز أول للمزارع:\n- بط مولار بكيني هجين (عمر يوم): 13.50 ج.م\n- بط بكيني مزارع نخب أول: 6.50 ج.م\n- بيض تفريخ مائي: 6.20 ج.م\n- بط مسكوفي أصلي بري (عمر يوم): 17.00 ج.م\n\n🐥 الكتاكيت والأهالي:\n- كتكوت أبيض مزارع: 12.50 ج.م\n- كتكوت ساسو شفر: 6.25 ج.م\n- كتكوت بلدي هجين متميز: 4.50 ج.م\n\n🌾 الأعلاف اليوم:\nطن بادي 23% سوبر: 22,600 ج.م",
    prices: {
      white_poultry: 85,
      sass_poultry: 106,
      baladi_poultry: 138,
      mothers_poultry: 72,
      white_chick_corp: 12.5,
      white_chick_dist: 12,
      sass_chick: 6.25,
      sass_chick_2nd: 5.8,
      baladi_chick: 4.5,
      baladi_chick_hybrid: 4.5,
      rozzi_chick: 6.9,
      rozzi_chick_braber: 5.4,
      duck_french: 13.5,
      duck_pekin_farms: 6.5,
      duck_pekin_egg: 6.2,
      duck_muscovy_1day: 17,
      feed_badi: 22600,
      feed_nami: 22200,
      feed_nahi: 21900,
      egg_white: 153,
      egg_red: 158
    }
  },
  {
    id: "tareq-halla",
    name: "بورصة طارق هلا للبيض والبلديات",
    owner: "المهندس طارق هلا",
    city: "ديرب نجم",
    locationDetails: "ديرب نجم، الشارع التجاري الرئيسي",
    phone: "01004556100",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "بيض مزارع (أبيض، أحمر، بلدي)، كتاكيت بيض بياض",
    badgeEmoji: "🥚",
    popularity: "شعبية",
    contactsCount: "أقوى حلقة وصل لبيع وشراء البيض بالشرقية والدقهلية",
    bulletinText: "🥚 نشرة المهندس طارق هلا لكرتونة البيض والبلديات:\n\nمستقرون ومنظمون لحفظ حقوق المنتجين بالمزارع:\n- كرتونة بيض أبيض مزارع (تسليم بلدي): 150.00 ج.م\n- كرتونة بيض أحمر (سوبر أرضيات): 155.00 ج.م\n- كرتونة بيض بلدي أصيل: 135.00 ج.م\n\n🐥 كتاكيت البيض البياض:\n- كتكوت بلدي بيور بياض ممتاز: 4.50 ج.م\n- كتكوت ساسو ثقيل مع حيوية ممتازة: 5.80 ج.م\n- كتكوت بلدي هجين: 4.20 ج.م\n\nنضمن النظافة وسلامة القشرة دائماً.",
    prices: {
      white_poultry: 83,
      sass_poultry: 104,
      baladi_poultry: 135,
      mothers_poultry: 71,
      white_chick_corp: 12.2,
      white_chick_dist: 11.8,
      sass_chick: 5.8,
      sass_chick_2nd: 5.3,
      baladi_chick: 4.5,
      baladi_chick_hybrid: 4.2,
      rozzi_chick: 6.7,
      rozzi_chick_braber: 5.1,
      duck_french: 11.8,
      duck_pekin_farms: 5.8,
      duck_pekin_egg: 5.5,
      duck_muscovy_1day: 15.5,
      feed_badi: 22450,
      feed_nami: 22050,
      feed_nahi: 21750,
      egg_white: 150,
      egg_red: 155,
      egg_baladi: 135
    }
  },
  {
    id: "makka-poultry",
    name: "مجموعة مكة وتطوير مزارع الشرقية",
    owner: "الدكتور أحمد الهواري",
    city: "الزقازيق",
    locationDetails: "الزقازيق، ميدان القنايات - مجمع العيادات البيطرية",
    phone: "01033221155",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "استشارات بيطرية، كتاكيت تسمين عالي المناعة والأدوية",
    badgeEmoji: "🛡️",
    popularity: "ممتازة",
    contactsCount: "المرجعية الأولى لمقاومة الأمراض الفيروسية والتحصين بالدلتا",
    bulletinText: "🛡️ نشرة مجموعة مكة والتحصين الشامل للمزارع:\n\nكتاكيت اليوم تم إعطاؤها جرعة اللينكو والسبكتين بالمعامل لمنع المشاكل التنفسية الأولى:\n- كتكوت أبيض شركات مكة (مناعة ممتازة): 12.20 ج.م\n- كتكوت ساسو جيل أول سوبر: 6.00 ج.م\n- كتكوت رزّي برابر للبيض الحصين: 5.50 ج.م\n\n🐖 لحوم الدواجن اليوم الحية بالمزرعة:\n- لحم أبيض تسمين: 84 ج.م تنفيذ\n- لحم ساسو أحمر: 105 ج.م بريمو\n\nتواصلوا معنا للحجز والدعم الطبي الشامل مجانًا.",
    prices: {
      white_poultry: 84,
      sass_poultry: 105,
      baladi_poultry: 140,
      mothers_poultry: 72,
      white_chick_corp: 12.2,
      white_chick_dist: 11.9,
      sass_chick: 6,
      sass_chick_2nd: 5.4,
      baladi_chick: 4.4,
      baladi_chick_hybrid: 4.4,
      rozzi_chick: 6.9,
      rozzi_chick_braber: 5.5,
      duck_french: 12.2,
      duck_pekin_farms: 6.1,
      duck_pekin_egg: 5.9,
      duck_muscovy_1day: 16.2,
      feed_badi: 22550,
      feed_nami: 22150,
      feed_nahi: 21850,
      egg_white: 151,
      egg_red: 156
    }
  },
  {
    id: "selim-feed",
    name: "مجموعة أولاد سليم للأعلاف والدواجن",
    owner: "الحاج عادل سليم",
    city: "أبو حماد",
    locationDetails: "أبو حماد، طريق بلبيس الزراعي بجوار محطة الكهرباء",
    phone: "01552300400",
    date: "اليوم الأربعاء ٣ يونيو ٢٠٢٦",
    type: "أعلاف مزارع أولاد سليم، كتاكيت تسمين قطعان",
    badgeEmoji: "🌾",
    popularity: "معتمدة",
    contactsCount: "مركز أبو حماد والقرين وحلقات التوزيع العالي للأعلاف",
    bulletinText: "🌾 نشرة أولاد سليم بالشرقية للأعلاف والدواجن:\n\nاليوم خصومات لأعضاء كبار المربين على طلبيات الأعلاف فوق 5 طن:\n- علف بادي 23% سوبر: 22,350 ج.م (توفير ممتاز بروتين نقي)\n- علف نامي 21% سوبر: 21,950 ج.م\n- علف ناهي 19% سوبر: 21,650 ج.م\n\n🐣 كتاكيت التسمين والأهالي:\n- كتكوت أبيض شركات: 11.90 ج.م\n- كتكوت أبيض أهالي مصلصال: 11.40 ج.م\n- كتكوت ساسو شفر لحوم: 5.60 ج.م\n- كتكوت بلدي بيور بياض: 4.30 ج.م\n\nأصحاب مزارع التسمين مرحب بكم دوماً.",
    prices: {
      white_poultry: 83.5,
      sass_poultry: 104.5,
      baladi_poultry: 139,
      mothers_poultry: 71.5,
      white_chick_corp: 11.9,
      white_chick_dist: 11.4,
      sass_chick: 5.6,
      sass_chick_2nd: 5.1,
      baladi_chick: 4.3,
      baladi_chick_hybrid: 4.3,
      rozzi_chick: 6.6,
      rozzi_chick_braber: 5,
      duck_french: 11.5,
      duck_pekin_farms: 5.9,
      duck_pekin_egg: 5.7,
      duck_muscovy_1day: 15.8,
      feed_badi: 22350,
      feed_nami: 21950,
      feed_nahi: 21650,
      egg_white: 149,
      egg_red: 154
    }
  }
];
